version: "2"         # required to adjust maintainability checks
plugins:
  swiftlint:
    enabled: true
  duplication:
    enabled: false # disabling due to many false-positives on repeated func argument lists
checks:
  argument-count:
    config:
      threshold: 7 # we have some funcs with lots of arguments but many have defaults
  complex-logic:
    config:
      threshold: 14 # networking is hard =/
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 14 # hard
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 40 # lol networking is hard?
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 5
  # similar-code:
  #   config:
  #     threshold: # language-specific defaults. an override will affect all languages.
  # identical-code:
  #   config:
  #     threshold: # language-specific defaults. an override will affect all languages.